version: '3.3'
services:
  chakornhello:
    image: rancher/hello-world:latest
    networks:
      - webproxy
    logging:
      driver: json-file
    deploy:
      replicas: 2
      labels:
        traefik.docker.network: webproxy
        traefik.enable: 'true'
        traefik.http.routers.chakornhello-https.entrypoints: websecure
        traefik.http.routers.chakornhello-https.rule: Host(`chakornhello.xops.ipv9.xyz`)
        traefik.http.routers.chakornhello-https.tls.certresolver: default
        traefik.http.services.chakornhello.loadbalancer.server.port: '80'
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.4'
          memory: 64M
networks:
  webproxy:
    external: true
