version: '3'

services:
  php:
    image: php:7.4-fpm-alpine
    container_name: php
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    #expose:
      #- "9000"
    networks:
      - webproxy   
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      #- ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      #- ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - webproxy
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.2"
          memory: 32M
        limits:
          cpus: "1.6"
          memory: 1G
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.chakornngin-https.rule=Host(`chakornngin.${DOMAIN}`)
        - traefik.http.routers.chakornngin-https.entrypoints=websecure
        - traefik.http.routers.chakornngin-https.tls.certresolver=default
        - traefik.http.services.chakornngin.loadbalancer.server.port=80

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: phpmyadmin
    restart: always
    networks:
      - webproxy
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - PMA_HOST=db
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.2"
          memory: 32M
        limits:
          cpus: "1.6"
          memory: 1G
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.chakornphp-https.rule=Host(`chakornphp.${DOMAIN}`)
        - traefik.http.routers.chakornphp-https.entrypoints=websecure
        - traefik.http.routers.chakornphp-https.tls.certresolver=default
        - traefik.http.services.chakornphp.loadbalancer.server.port=80

networks:
  default:
    name: web_network
    external: true
